### ISSUE TITLE
quartz相关的表大小写全都有问题

### ISSUE THREAD

**Issue by ieayoio** [CCweixiao/hbase-manager#2]
使用hbase2.x打包

运行java -jar  hbase-manager-admin-2.0.5.jar时候包如下错误
```
Caused by: java.sql.SQLSyntaxErrorException: Table 'hbase-manager.QRTZ_SIMPLE_TRIGGERS' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:974)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1113)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1381)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1046)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeUpdate(FilterChainImpl.java:3201)
        at com.alibaba.druid.filter.FilterAdapter.preparedStatement_executeUpdate(FilterAdapter.java:1092)
        at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeUpdate(FilterEventAdapter.java:491)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeUpdate(FilterChainImpl.java:3199)
        at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeUpdate(PreparedStatementProxyImpl.java:194)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:255)
        at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.clearData(StdJDBCDelegate.java:559)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.clearAllSchedulingData(JobStoreSupport.java:2013)
        ... 51 common frames omitted
```

文档中提到的quartz.sql，没有这个文件，运行hbase-manager-2.0.5.sql只包含小写名称的qrtz打头的表

**Comment by CCweixiao** [comment]
晚点会修复

**Comment by CCweixiao** [comment]
已经提供大写和小写的quartz.sql
